---
- hosts: webserver01 
  become: yes
  become_user: root
  tasks:

  - name: Create Docker folder
    become: yes
    become_user: root
    file: path=/root/Dockerfiles/ state=directory

  - name: Download Demo App in to server
    copy:
      src: kube-deplyment/iaacdemoapp.war
      dest: /root/Dockerfiles/iaacdemoapp.war 

  - name: Create Docker file
    copy: 
      src: kube-deplyment/Dockerfile
      dest: /root/Dockerfiles/Dockerfile

  - name: Create App Docker image  
    become: yes
    become_user: root
    command: "docker build -f /root/Dockerfiles/Dockerfile  -t iaacdemoapp /root/Dockerfiles/"
  
  - name: Deploy App on Kubernetes    
    command: "docker run -d -p 192.168.61.19:80:8080 --name iaacdemocon iaacdemoapp"

